version: '2'
services:
  mysql:
    image: mysql:latest
    mem_limit: 1024000000
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "plane"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
